services:
  backend:
    build:
      context: ./backend
    container_name: django_backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      DJANGO_DEBUG: 'True'
      DJANGO_SECRET_KEY: 'mysecretkey'
      DJANGO_ALLOWED_HOSTS: 'localhost,127.0.0.1'
      DATABASE_URL: 'postgres://postgres:password@db:5432/database'
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    container_name: nextjs_frontend
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production


  db:
    image: postgres:15  # Usando a imagem do PostgreSQL versão 15
    container_name: postgres_db
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"  # Porta padrão do PostgreSQL

volumes:
  postgres_data:
