version: '3.8'

services:
  backend:
    build:
      context: ./backend  # Caminho para o diret처rio do backend
    container_name: django_backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      DJANGO_DEBUG: 'True'
      DJANGO_SECRET_KEY: 'mysecretkey'
      DJANGO_ALLOWED_HOSTS: 'localhost,127.0.0.1'
      DATABASE_URL: 'postgres://myuser:mypassword@db:5432/mydatabase'
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend  # Caminho para o diret처rio do frontend
    container_name: nextjs_frontend
    command: npm run dev
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development

  db:
    image: postgres:15  # Usando a imagem do PostgreSQL vers찾o 15
    container_name: postgres_db
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"  # Porta padr찾o do PostgreSQL

volumes:
  postgres_data:
