# Generated by Django 5.1.2 on 2024-10-11 02:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sgset', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CursoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('turma', models.CharField(max_length=50)),
                ('turno', models.CharField(max_length=50)),
                ('modalidade', models.CharField(max_length=50)),
                ('periodo_de', models.DateField()),
                ('periodo_ate', models.DateField()),
                ('atendimento', models.CharField(max_length=50)),
                ('horario_de', models.TimeField()),
                ('horario_ate', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='DocenteModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='MatriculaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_estudantes_estimados', models.PositiveIntegerField()),
                ('numero_estudantes_realizados', models.PositiveIntegerField()),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sgset.cursomodel')),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sgset.docentemodel')),
            ],
        ),
    ]
