# Generated by Django 5.1.2 on 2024-10-18 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sgset', '0004_courseclass_duration_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClassSchedule',
            new_name='ClassScheduleModel',
        ),
        migrations.RenameModel(
            old_name='CourseClass',
            new_name='CourseClassModel',
        ),
        migrations.RenameModel(
            old_name='Course',
            new_name='CourseModel',
        ),
        migrations.RenameModel(
            old_name='DayOfWeek',
            new_name='DayOfWeekModel',
        ),
        migrations.RenameModel(
            old_name='Event',
            new_name='EventModel',
        ),
        migrations.RenameModel(
            old_name='Goal',
            new_name='GoalModel',
        ),
        migrations.RenameModel(
            old_name='InstructorClass',
            new_name='InstructorClassModel',
        ),
        migrations.RenameModel(
            old_name='Instructor',
            new_name='InstructorModel',
        ),
    ]
