# Generated by Django 5.1.2 on 2024-10-18 23:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgset', '0005_rename_classschedule_classschedulemodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmodel',
            name='instructor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instructor', to='sgset.instructormodel'),
        ),
    ]
