# Generated by Django 5.1.2 on 2024-11-22 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sgset', '0006_eventmodel_instructor'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DayOfWeekModel',
            new_name='DayOfWeek',
        ),
        migrations.RenameModel(
            old_name='GoalModel',
            new_name='Goal',
        ),
    ]
