# Generated by Django 5.1.2 on 2024-11-21 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sgset', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GoalModel',
            new_name='Goal',
        ),
        migrations.RenameModel(
            old_name='InstructorModel',
            new_name='Instructor',
        ),
        migrations.RenameModel(
            old_name='InstructorClassModel',
            new_name='InstructorClass',
        ),
    ]
