# Generated by Django 5.1.2 on 2024-11-22 23:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgset', '0003_days_of_week'),
    ]

    operations = [
        migrations.CreateModel(
            name='SGSETModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('curso', models.CharField(blank=True, max_length=255, null=True, verbose_name='Course Name')),
                ('turma', models.CharField(blank=True, default='000000', max_length=100, verbose_name='Class')),
                ('situacao', models.CharField(blank=True, max_length=50, null=True, verbose_name='Situation')),
                ('turno', models.CharField(blank=True, max_length=20, null=True, verbose_name='Shift')),
                ('carga_horaria', models.IntegerField(blank=True, null=True, verbose_name='Workload (hours)')),
                ('no_de_matriculas_realizado', models.IntegerField(blank=True, null=True, verbose_name='Actual Enrollment')),
                ('no_de_matriculas_estimado', models.IntegerField(blank=True, null=True, verbose_name='Estimated Enrollment')),
                ('periodo_de', models.DateTimeField(blank=True, null=True, verbose_name='Start Date')),
                ('periodo_ate', models.DateTimeField(blank=True, null=True, verbose_name='End Date')),
                ('horario_de', models.TimeField(blank=True, null=True, verbose_name='Start Time')),
                ('horario_ate', models.TimeField(blank=True, null=True, verbose_name='End Time')),
                ('dia_da_semana', models.CharField(blank=True, max_length=255, null=True, verbose_name='Days of the Week')),
                ('modalidade', models.CharField(blank=True, max_length=100, null=True, verbose_name='Modality')),
                ('municipio', models.CharField(blank=True, max_length=100, null=True, verbose_name='City')),
                ('atendimento', models.CharField(blank=True, max_length=100, null=True, verbose_name='Service Type')),
                ('preco_por_participante', models.CharField(blank=True, max_length=50, null=True, verbose_name='Price per Participant')),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Value')),
            ],
            options={
                'ordering': ['periodo_de'],
            },
        ),
    ]
